- hosts: all
  gather_facts: no
  collections:
    - community.general
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "../privkey"

  tasks:
   - name: Dependancies
     apt:
       name: 
        - ansible
        - git
       update_cache: yes
     when: inventory_hostname == groups['master'][0]

   - name: Downloading k3s-ansible
     ansible.builtin.git:
       repo: 'https://github.com/k3s-io/k3s-ansible'
       dest: /opt/k3s-ansible
     when: inventory_hostname == groups['master'][0]

   - name: overwrite sample inventory
     ansible.builtin.copy:
       src: '../inv_internal.ini'
       dest: /opt/k3s-ansible/inventory/sample/hosts.ini
     when: inventory_hostname == groups['master'][0]

   - name: Running shell command
     ansible.builtin.shell: ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /opt/k3s-ansible/inventory/sample/hosts.ini /opt/k3s-ansible/site.yml -e ansible_user=root
     when: inventory_hostname == groups['master'][0]

