- hosts: all
  gather_facts: no
  collections:
    - community.general
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "../privkey"

  tasks:
   - name: generate SSH key
     user:
       name: "root"
       generate_ssh_key: yes
       ssh_key_type: rsa
       ssh_key_bits: 4096
       ssh_key_file: .ssh/id_rsa
       force: no
     when: inventory_hostname == groups['master'][0]

   - name: Fetch the ssh_key of master 0
     ansible.builtin.fetch:
       src: /root/.ssh/id_rsa.pub
       dest: /tmp/kube_master_ssh.pub
       flat: yes
     when: inventory_hostname == groups['master'][0]
       
   - name: Set authorized key with the new key
     ansible.posix.authorized_key:
       user: root
       state: present
       key: "{{ lookup('file', '/tmp/kube_master_ssh.pub') }}"
